version: 2
jobs:
  build:
    working_directory: /go/src/github.com/tjololo/dunix
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure -v
      - run: go test -v -race $(go list ./... | grep -v /vendor/)
